name: "Update server"
on:
  schedule:
    - cron: '0 0 * * *'
jobs:
  update-server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install python-dotenv
          pip install newspaper4k
      - name: Run update_server.py
        env:
          NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}
        run: python update_server.py
      - name: Commit and push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add news.db
          git commit -m "Update server"
          git push origin main
